### PR TITLE
pass-through-messaging-ballerina

### PR DESCRIPTION
**Pull request by sanethmaduranga**
## Purpose
adding sample use case scenario.

## Goals
provide complete guide for the use case

## Approach
all are included in README.md file.

## Release note
Ballerina 0.970.1

## Documentation
N/A

## Training
Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
  include in the README.md file

## Samples
 inside the file.

## Related PRs
 List any other related PRs

## Migrations (if applicable)
 Describe migration steps and platforms on which migration has been tested

## Test environment
 JDK 8
 UBUNTU - 16.04 LTS

## Learning
Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

### CODE REVIEW

**Comment by dushansachinda** [comment]
In the meantime, please double check for grammar error and spelling mistakes

**Comment by sanethmaduranga** [comment]
Hi,
I made the changes according to the comments. Please refer to the latest files and let me know if there are any further issues.

**Comment by kasun04** [comment]
Can we set up Testerina tests and Travis CI for the repository? Please have a look at existing guides on how to do this.

**Comment by sanethmaduranga** [comment]
Hi
I set up the Travis Cl and tests. I changed it to 'ballerina-guides' instead of the forked repo. So it will work, after merging. I checked it for forked repo.

**Pull request merged**
